"""add performance indexes

Revision ID: 026a415c3085
Revises: a3d83c3aef1c
Create Date: 2026-07-08 08:35:27.131943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026a415c3085'
down_revision: Union[str, None] = 'a3d83c3aef1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_maker', ['maker'], unique=False)
        batch_op.create_index('idx_tasks_rating', ['rating'], unique=False)
        batch_op.create_index('idx_tasks_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_status_created')
        batch_op.drop_index('idx_tasks_rating')
        batch_op.drop_index('idx_tasks_maker')

    # ### end Alembic commands ###
