"""add new_releases table

Revision ID: 1eaa5db34e11
Revises: 2f2a4187c264
Create Date: 2026-07-08 07:17:28.685140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaa5db34e11'
down_revision: Union[str, None] = '2f2a4187c264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_releases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('video_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('added_to_library', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('new_releases', schema=None) as batch_op:
        batch_op.create_index('idx_new_releases_actor', ['actor_id'], unique=False)
        batch_op.create_index('idx_new_releases_code', ['video_code'], unique=False)
        batch_op.create_index('idx_new_releases_unread', ['is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_releases', schema=None) as batch_op:
        batch_op.drop_index('idx_new_releases_unread')
        batch_op.drop_index('idx_new_releases_code')
        batch_op.drop_index('idx_new_releases_actor')

    op.drop_table('new_releases')
    # ### end Alembic commands ###
