"""add subscriptions table

Revision ID: 2f2a4187c264
Revises: 4493ee991738
Create Date: 2026-07-04 08:31:33.858376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2a4187c264'
down_revision: Union[str, None] = '4493ee991738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sub_type', sa.String(length=20), nullable=False),
    sa.Column('rank_type', sa.String(length=20), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('auto_add', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('target_list_source_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('check_interval_hours', sa.Integer(), server_default='6', nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_list_source_id'], ['list_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_subscriptions_actor', ['actor_id'], unique=False)
        batch_op.create_index('idx_subscriptions_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_subscriptions_type', ['sub_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_subscriptions_type')
        batch_op.drop_index('idx_subscriptions_enabled')
        batch_op.drop_index('idx_subscriptions_actor')

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
