"""initial schema

Revision ID: 4493ee991738
Revises: 
Create Date: 2026-07-01 14:57:30.219438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4493ee991738'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_local', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('cup', sa.String(length=10), nullable=True),
    sa.Column('measurements', sa.String(length=50), nullable=True),
    sa.Column('debut_date', sa.String(length=20), nullable=True),
    sa.Column('movie_count', sa.Integer(), nullable=True),
    sa.Column('is_followed', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.create_index('idx_actors_blacklisted', ['is_blacklisted'], unique=False)
        batch_op.create_index('idx_actors_followed', ['is_followed'], unique=False)
        batch_op.create_index('idx_actors_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_actors_name'), ['name'], unique=False)

    op.create_table('list_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_code', sa.String(length=50), nullable=False),
    sa.Column('list_path', sa.String(length=200), nullable=False),
    sa.Column('list_params', sa.String(length=100), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('last_scanned_page', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_code')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_source_id', sa.Integer(), nullable=True),
    sa.Column('crawl_type', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['list_source_id'], ['list_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_logs', schema=None) as batch_op:
        batch_op.create_index('idx_crawl_logs_created', ['created_at'], unique=False)
        batch_op.create_index('idx_crawl_logs_source', ['list_source_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('best_magnet', sa.Text(), nullable=True),
    sa.Column('magnets_json', sa.Text(), nullable=True),
    sa.Column('video_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_urls', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('maker', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('series', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('file_size', sa.String(length=20), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('favorite_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('view_status', sa.String(length=20), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_title_translated', sa.String(length=500), nullable=True),
    sa.Column('ai_tags', sa.Text(), nullable=True),
    sa.Column('media_in_library', sa.Boolean(), nullable=True),
    sa.Column('download_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['list_source_id'], ['list_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_favorite', ['is_favorite', 'favorite_at'], unique=False)
        batch_op.create_index('idx_tasks_list_status', ['list_source_id', 'status'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_tasks_video_code', ['video_code'], unique=False)
        batch_op.create_index('idx_tasks_view_status', ['view_status'], unique=False)

    op.create_table('actor_movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor_movies', schema=None) as batch_op:
        batch_op.create_index('idx_actor_movies_actor', ['actor_id'], unique=False)
        batch_op.create_index('idx_actor_movies_task', ['task_id'], unique=False)

    op.create_table('rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rank_type', sa.String(length=20), nullable=False),
    sa.Column('rank_date', sa.String(length=20), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('video_code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('is_in_library', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.create_index('idx_rankings_type_date', ['rank_type', 'rank_date'], unique=False)
        batch_op.create_index('idx_rankings_video_code', ['video_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_index('idx_rankings_video_code')
        batch_op.drop_index('idx_rankings_type_date')

    op.drop_table('rankings')
    with op.batch_alter_table('actor_movies', schema=None) as batch_op:
        batch_op.drop_index('idx_actor_movies_task')
        batch_op.drop_index('idx_actor_movies_actor')

    op.drop_table('actor_movies')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_view_status')
        batch_op.drop_index('idx_tasks_video_code')
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_list_status')
        batch_op.drop_index('idx_tasks_favorite')

    op.drop_table('tasks')
    with op.batch_alter_table('crawl_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_crawl_logs_source')
        batch_op.drop_index('idx_crawl_logs_created')

    op.drop_table('crawl_logs')
    op.drop_table('settings')
    op.drop_table('list_sources')
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actors_name'))
        batch_op.drop_index('idx_actors_name')
        batch_op.drop_index('idx_actors_followed')
        batch_op.drop_index('idx_actors_blacklisted')

    op.drop_table('actors')
    # ### end Alembic commands ###
