"""Phase5 cleanup

Revision ID: 568e1c94c2c8
Revises: 026a415c3085
Create Date: 2026-07-08 08:37:03.991983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568e1c94c2c8'
down_revision: Union[str, None] = '026a415c3085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.drop_index('ix_actors_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.create_index('ix_actors_name', ['name'], unique=False)

    # ### end Alembic commands ###
