"""add downloads table

Revision ID: 631485cdd57b
Revises: 37a30a23b795
Create Date: 2026-07-08 07:31:12.658151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631485cdd57b'
down_revision: Union[str, None] = '37a30a23b795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('video_code', sa.String(length=50), nullable=True),
    sa.Column('magnet', sa.Text(), nullable=False),
    sa.Column('info_hash', sa.String(length=40), nullable=True),
    sa.Column('downloader', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pushed', nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index('idx_downloads_downloader', ['downloader'], unique=False)
        batch_op.create_index('idx_downloads_status', ['status'], unique=False)
        batch_op.create_index('idx_downloads_task', ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_info_hash'), ['info_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloads_info_hash'))
        batch_op.drop_index('idx_downloads_task')
        batch_op.drop_index('idx_downloads_status')
        batch_op.drop_index('idx_downloads_downloader')

    op.drop_table('downloads')
    # ### end Alembic commands ###
