"""add llm_cache and content_filter_rules

Revision ID: 7d9b6b8cac2d
Revises: 85251192b82e
Create Date: 2026-07-08 07:23:54.312902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9b6b8cac2d'
down_revision: Union[str, None] = '85251192b82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_filter_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('is_regex', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('action', sa.String(length=20), server_default='hide', nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_filter_rules', schema=None) as batch_op:
        batch_op.create_index('idx_filter_rules_enabled', ['enabled'], unique=False)

    op.create_table('llm_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_cache_prompt_hash'), ['prompt_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_cache_prompt_hash'))

    op.drop_table('llm_cache')
    with op.batch_alter_table('content_filter_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_filter_rules_enabled')

    op.drop_table('content_filter_rules')
    # ### end Alembic commands ###
