"""add insight_reports table

Revision ID: 85251192b82e
Revises: 1eaa5db34e11
Create Date: 2026-07-08 07:20:28.406568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85251192b82e'
down_revision: Union[str, None] = '1eaa5db34e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('stats_json', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insight_reports', schema=None) as batch_op:
        batch_op.create_index('idx_insight_reports_month', ['month'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_insight_reports_month')

    op.drop_table('insight_reports')
    # ### end Alembic commands ###
